CaparKurye/Areas/Admin/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaparKurye.AC;
using System.IO;

namespace CaparKurye.Areas.Admin.Controllers
{
    public class BankAccountsController : Controller
    {
        private AC.AppContext db = new AC.AppContext();

        // GET: BankAccounts
        public ActionResult Index()
        {
            var bankAccounts = db.BankAccounts.ToList();
            return View(bankAccounts);
        }

        // GET: BankAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccounts bankAccounts = db.BankAccounts.Find(id);
            if (bankAccounts == null)
            {
                return HttpNotFound();
            }
            return View(bankAccounts);
        }

        // GET: BankAccounts/Create
        public ActionResult Create()
        {
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name");
            return View();
        }

        // POST: BankAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "accountID,bankName,ibanCode,branchCode,accountCode,pictureID")] BankAccounts bankAccounts, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.AddHours(11).ToString("MM-dd-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/public/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        Pictures pictures = new Pictures();
                        pictures.title = file.FileName;
                        pictures.name = file.FileName;
                        db.Pictures.Add(pictures);
                        db.SaveChanges();
                        bankAccounts.pictureID = pictures.pictureID;
                    }
                }
                db.BankAccounts.Add(bankAccounts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title", bankAccounts.pictureID);
            return View(bankAccounts);
        }

        // GET: BankAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccounts bankAccounts = db.BankAccounts.Find(id);
            if (bankAccounts == null)
            {
                return HttpNotFound();
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title", bankAccounts.pictureID);
            return View(bankAccounts);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "accountID,bankName,ibanCode,branchCode,accountCode,pictureID")] BankAccounts bankAccounts, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.AddHours(11).ToString("MM-dd-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/public/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        Pictures pictures = new Pictures();
                        pictures.title = file.FileName;
                        pictures.name = file.FileName;
                        db.Pictures.Add(pictures);
                        db.SaveChanges();
                        bankAccounts.pictureID = pictures.pictureID;
                    }
                }
                BankAccounts bnk = db.BankAccounts.Find(bankAccounts.accountID);
                bnk.accountCode = bankAccounts.accountCode;
                bnk.bankName = bankAccounts.bankName;
                bnk.ibanCode = bankAccounts.ibanCode;
                bnk.branchCode = bankAccounts.branchCode;
                bnk.pictureID = bankAccounts.pictureID;
                db.Entry(bnk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title", bankAccounts.pictureID);
            return View(bankAccounts);
        }

        // GET: BankAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccounts bankAccounts = db.BankAccounts.Find(id);
            if (bankAccounts == null)
            {
                return HttpNotFound();
            }
            return View(bankAccounts);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BankAccounts bankAccounts = db.BankAccounts.Find(id);
            db.BankAccounts.Remove(bankAccounts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaparKurye/Areas/Admin/Views/BankAccounts/Create.cshtml
@model CaparKurye.BankAccounts

@{
    ViewBag.Title = "Banka Hesapları";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script>

    function changeType(val) {
        if (val == "choose1") {
            $("#choose1").hide();
            $("#choose2").show();
        } else {
            $("#choose1").show();
            $("#choose2").hide();
        }
    }
</script>

<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-credit-card-alt" aria-hidden="true"></i> @ViewBag.Title</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">

            @using (Html.BeginForm("Create", "BankAccounts", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.bankName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.bankName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.bankName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ibanCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ibanCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ibanCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.branchCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.branchCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.branchCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.accountCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.accountCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.accountCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Yükleme Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <select name="uploadType" class="form-control class=" col-md-10"" onclick="changeType(this.value)">
                            <option value="choose2">Resim Yükle</option>
                            <option value="choose1">Önceki Resimlerden Seç</option>
                        </select>
                    </div>
                </div>

                <div class="form-group" id="choose1">
                    @Html.Label("Resim Yükle:", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <input type="file" name="file" id="file" class="form-control" accept="image/*" style="width: 100%;" />
                    </div>
                </div>

                <div class="form-group" id="choose2" style="display:none">
                    @Html.LabelFor(model => model.pictureID, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.DropDownList("pictureID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.pictureID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-offset-2 col-md-4 col-xs-6">
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-success pull-left" />
                    </div>
                </div>

            }
            <div class="col-xs-6 col-md-4">
                <div class="form-group">
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default pull-right" })
                </div>
            </div>

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/BankAccounts/Delete.cshtml
@model CaparKurye.BankAccounts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BankAccounts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.bankName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bankName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ibanCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ibanCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.branchCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.branchCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.accountCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.accountCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pictures.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pictures.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CaparKurye/Areas/Admin/Views/BankAccounts/Details.cshtml
@model CaparKurye.BankAccounts

@{
    ViewBag.Title = "Banka Hesabları";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-credit-card-alt" aria-hidden="true"></i> @ViewBag.Title</h4>

        <div class="col-xs-12">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.bankName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.bankName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ibanCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ibanCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.branchCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.branchCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.accountCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.accountCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Pictures.name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Pictures.name)
                </dd>
            </dl>

            <div class="form-group pull-left">@Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default pull-right" })</div>

            @if (Session["adminType"].ToString() == "Admin")
            {
                <div class="form-group pull-right">
                    @Html.ActionLink("Düzenle", "Edit", new { id = Model.accountID }, new { @class = "btn btn-primary" })
                </div>
            }

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/BankAccounts/Edit.cshtml
@model CaparKurye.BankAccounts

@{
    ViewBag.Title = "Banka Hesapları";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script>
    function changeType(val) {
        if (val == "choose1") {
            $("#choose1").hide();
            $("#choose2").show();
        } else {
            $("#choose1").show();
            $("#choose2").hide();
        }
    }
</script>

<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-credit-card-alt" aria-hidden="true"></i> @ViewBag.Title</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">

            @using (Html.BeginForm("Edit", "BankAccounts", FormMethod.Post, new { id = Model.accountID, enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.accountID)

                <div class="form-group">
                    @Html.LabelFor(model => model.bankName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.bankName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.bankName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ibanCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ibanCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ibanCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.branchCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.branchCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.branchCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.accountCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.accountCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.accountCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Yükleme Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <select name="uploadType" class="form-control class=" col-md-10"" onclick="changeType(this.value)">
                            <option value="choose2">Resim Yükle</option>
                            <option value="choose1">Önceki Resimlerden Seç</option>
                        </select>
                    </div>
                </div>

                <div class="form-group" id="choose1">
                    @Html.Label("Resim Yükle:", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <input type="file" name="file" id="file" class="form-control" accept="image/*" style="width: 100%;" />
                    </div>
                </div>

                <div class="form-group" id="choose2" style="display:none">
                    @Html.LabelFor(model => model.pictureID, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.DropDownList("pictureID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.pictureID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-offset-2 col-md-4 col-xs-6">
                    <div class="form-group pull-left">
                        <input type="submit" value="Güncelle" class="btn btn-success" />
                    </div>
                </div>

            }
            <div class="col-xs-6 col-md-4">
                <div class="form-group pull-right">
                    <div style="display:inline-block">
                        @using (Html.BeginForm("Delete", "BankAccounts", new { id = Model.accountID }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="submit" value="Sil" class="btn btn-danger" />
                        }
                    </div>
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/BankAccounts/Index.cshtml
@model IEnumerable<CaparKurye.BankAccounts>

@{
    ViewBag.Title = "Banka Hesapları";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="col-xs-12 col-sm-12">

    <div class="page">

        <h4 class="title"><i class="fa fa-credit-card-alt" aria-hidden="true"></i> @ViewBag.Title</h4>
        <div class="col-xs-12 col-sm-12">

            <table class="table">
                <tr>
                    <th>Resim</th>
                    <th>@Html.DisplayNameFor(model => model.bankName)</th>
                    <th>@Html.DisplayNameFor(model => model.ibanCode)</th>
                    <th>@Html.DisplayNameFor(model => model.branchCode)</th>
                    <th>@Html.DisplayNameFor(model => model.accountCode)</th>
                    <th>
                        @if (Session["adminType"].ToString() == "Admin")
                        {
                            @Html.ActionLink("Yeni Ekle", "Create", new { }, new { @class = "btn btn-primary btn-xs pull-right" })
                        }
                    </th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            <img style="height:50px;width:50px;" src="@Url.Content("~/public/UploadedFiles/")@Html.DisplayFor(modelItem => item.Pictures.name)" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.bankName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ibanCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.branchCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.accountCode)
                        </td>
                        <td class="text-right">

                            @if (Session["adminType"].ToString() == "Admin")
                {
                                @Html.ActionLink("Düzenle", "Edit", new { id = item.accountID }, new { @class = "btn btn-warning btn-xs" })
                            }

                        </td>
                    </tr>
                }

            </table>

        </div>
    </div>
</div>