CaparKurye/Areas/Admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaparKurye.AC;
using System.IO;
using System.Globalization;

namespace CaparKurye.Areas.Admin.Controllers
{
    public class SlidersController : Controller
    {
        private AC.AppContext db = new AC.AppContext();

        public bool UserCheck()
        {
            if (Session["adminID"] != null && Session["adminName"] != null)
            {
                TempData["Message"] = null;
                return true;
            }
            else
            {
                TempData["Message"] = "Lütfen Admin Girişi Yapınız";
                return false;
            }
        }

        // GET: Sliders
        public ActionResult Index()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            var sliders = db.Sliders.Include(s => s.Pictures);
            return View(sliders.ToList());
        }

        // GET: Sliders/Details/5
        public ActionResult Details(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sliders sliders = db.Sliders.Find(id);
            if (sliders == null)
            {
                return HttpNotFound();
            }
            return View(sliders);
        }

        // GET: Sliders/Create
        public ActionResult Create()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name");
            return View();
        }

        // POST: Sliders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "sliderID,title,content,pictureID,url,order")] Sliders sliders, HttpPostedFileBase file)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.AddHours(11).ToString("MM-dd-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/public/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        Pictures pictures = new Pictures();
                        pictures.title = file.FileName;
                        pictures.name = file.FileName;
                        db.Pictures.Add(pictures);
                        db.SaveChanges();
                        sliders.pictureID = pictures.pictureID;
                    }
                }
                db.Sliders.Add(sliders);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name", sliders.pictureID);
            return View(sliders);
        }

        // GET: Sliders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sliders sliders = db.Sliders.Find(id);
            if (sliders == null)
            {
                return HttpNotFound();
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name", sliders.pictureID);
            return View(sliders);
        }

        // POST: Sliders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "sliderID,title,content,pictureID,url,order")] Sliders sliders, HttpPostedFileBase file)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.AddHours(11).ToString("MM-dd-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/public/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        Pictures pictures = new Pictures();
                        pictures.title = file.FileName;
                        pictures.name = file.FileName;
                        db.Pictures.Add(pictures);
                        db.SaveChanges();
                        sliders.pictureID = pictures.pictureID;
                    }
                }
                db.Entry(sliders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name", sliders.pictureID);
            return View(sliders);
        }

        // GET: Sliders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sliders sliders = db.Sliders.Find(id);
            if (sliders == null)
            {
                return HttpNotFound();
            }
            return View(sliders);
        }

        // POST: Sliders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            Sliders sliders = db.Sliders.Find(id);
            db.Sliders.Remove(sliders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaparKurye/Areas/Admin/Views/Sliders/Create.cshtml
@model CaparKurye.Sliders

@{
    ViewBag.Title = "Slider";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script>
    function changeType(val) {
        if (val == "choose1") {
            $("#choose1").hide();
            $("#choose2").show();
        } else {
            $("#choose1").show();
            $("#choose2").hide();
        }
    }
</script>
<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-exchange" aria-hidden="true"></i> @ViewBag.Title</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">

            @using (Html.BeginForm("Create", "Sliders", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Yükleme Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <select name="uploadType" class="form-control class=" col-md-10"" onclick="changeType(this.value)">
                            <option value="choose2">Resim Yükle</option>
                            <option value="choose1">Önceki Resimlerden Seç</option>
                        </select>
                    </div>
                </div>

                <div class="form-group" id="choose1">
                    @Html.Label("Resim Yükle:", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <input type="file" name="file" id="file" class="form-control" accept="image/*" style="width: 100%;" />
                    </div>
                </div>

                <div class="form-group" id="choose2" style="display:none">
                    @Html.LabelFor(model => model.pictureID, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.DropDownList("pictureID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.pictureID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.order, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.order, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.order, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-offset-2 col-md-4 col-xs-6">
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-success pull-left" />
                    </div>
                </div>

            }
            <div class="col-xs-6 col-md-4">
                <div class="form-group">
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default pull-right" })
                </div>
            </div>

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/Sliders/Delete.cshtml
@model CaparKurye.Sliders

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sliders</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pictures.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pictures.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CaparKurye/Areas/Admin/Views/Sliders/Details.cshtml
@model CaparKurye.Sliders

@{
    ViewBag.Title = "Slider";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-exchange" aria-hidden="true"></i> @ViewBag.Title</h4>

        <div class="col-xs-12">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.content)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.content)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.url)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.url)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.order)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.order)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Pictures.name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Pictures.name)
                </dd>
            </dl>

            <div class="form-group pull-left">@Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default pull-right" })</div>

            @if (Session["adminType"].ToString() == "Admin")
            {
                <div class="form-group pull-right">
                    @Html.ActionLink("Düzenle", "Edit", new { id = Model.sliderID }, new { @class = "btn btn-primary" })
                </div>
            }

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/Sliders/Edit.cshtml
@model CaparKurye.Sliders

@{
    ViewBag.Title = "Slider";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script>
    function changeType(val) {
        if (val == "choose1") {
            $("#choose1").hide();
            $("#choose2").show();
        } else {
            $("#choose1").show();
            $("#choose2").hide();
        }
    }
</script>
<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-exchange" aria-hidden="true"></i> @ViewBag.Title</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">

            @using (Html.BeginForm("Edit", "Sliders", FormMethod.Post, new { id = Model.sliderID, enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.sliderID)

                <div class="form-group">
                    @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Yükleme Tipi", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <select name="uploadType" class="form-control class=" col-md-10"" onclick="changeType(this.value)">
                            <option value="choose2">Resim Yükle</option>
                            <option value="choose1">Önceki Resimlerden Seç</option>
                        </select>
                    </div>
                </div>

                <div class="form-group" id="choose1">
                    @Html.Label("Resim Yükle:", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <input type="file" name="file" id="file" class="form-control" accept="image/*" style="width: 100%;" />
                    </div>
                </div>

                <div class="form-group" id="choose2" style="display:none">
                    @Html.LabelFor(model => model.pictureID, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.DropDownList("pictureID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.pictureID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.order, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.order, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.order, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-offset-2 col-md-4 col-xs-6">
                    <div class="form-group pull-left">
                        <input type="submit" value="Güncelle" class="btn btn-success" />
                    </div>
                </div>

            }
            <div class="col-xs-6 col-md-4">
                <div class="form-group pull-right">
                    <div style="display:inline-block">
                        @using (Html.BeginForm("Delete", "Sliders", new { id = Model.sliderID }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="submit" value="Sil" class="btn btn-danger" />
                        }
                    </div>
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/Sliders/Index.cshtml
@model IEnumerable<CaparKurye.Sliders>

@{
    ViewBag.Title = "Slider";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="col-xs-12 col-sm-12">

    <div class="page">

        <h4 class="title"><i class="fa fa-exchange" aria-hidden="true"></i> @ViewBag.Title</h4>
        <div class="col-xs-12 col-sm-12">

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.order)
                    </th>
                    <th>Resim</th>
                    <th>
                        @Html.DisplayNameFor(model => model.title)
                    </th>
                    <th>
                        @if (Session["adminType"].ToString() == "Admin" || Session["adminType"].ToString() == "Asistan")
                        {
                            @Html.ActionLink("Yeni Ekle", "Create", new { }, new { @class = "btn btn-primary btn-xs pull-right" })
                        }
                    </th>
                </tr>

                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.order)
                        </td>
                        <td>
                            <img style="height:50px;width:50px;" src="@Url.Content("~/public/UploadedFiles/")@Html.DisplayFor(modelItem => item.Pictures.name)" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.title)
                        </td>

                        <td class="text-right">

                            @if (Session["adminType"].ToString() == "Admin" || Session["adminType"].ToString() == "Asistan")
                {
                                @Html.ActionLink("Düzenle", "Edit", new { id = item.sliderID }, new { @class = "btn btn-warning btn-xs" })
                            }

                        </td>
                    </tr>
                }

            </table>

        </div>
    </div>
</div>