CaparKurye/Areas/Admin/Controllers/FaqsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaparKurye.AC;

namespace CaparKurye.Areas.Admin.Controllers
{
    public class FaqsController : Controller
    {
        private AC.AppContext db = new AC.AppContext();

        public bool UserCheck()
        {
            if (Session["adminID"] != null && Session["adminName"] != null)
            {
                TempData["Message"] = null;
                return true;
            }
            else
            {
                TempData["Message"] = "Lütfen Admin Girişi Yapınız";
                return false;
            }
        }
        // GET: Faqs
        public ActionResult Index()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            return View(db.Faqs.ToList());
        }

        // GET: Faqs/Details/5
        public ActionResult Details(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faqs faqs = db.Faqs.Find(id);
            if (faqs == null)
            {
                return HttpNotFound();
            }
            return View(faqs);
        }

        // GET: Faqs/Create
        public ActionResult Create()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            return View();
        }

        // POST: Faqs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "faqID,category,question,answer")] Faqs faqs)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (ModelState.IsValid)
            {
                db.Faqs.Add(faqs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(faqs);
        }

        // GET: Faqs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faqs faqs = db.Faqs.Find(id);
            if (faqs == null)
            {
                return HttpNotFound();
            }
            return View(faqs);
        }

        // POST: Faqs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "faqID,category,question,answer")] Faqs faqs)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (ModelState.IsValid)
            {
                db.Entry(faqs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faqs);
        }

        // GET: Faqs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faqs faqs = db.Faqs.Find(id);
            if (faqs == null)
            {
                return HttpNotFound();
            }
            return View(faqs);
        }

        // POST: Faqs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            Faqs faqs = db.Faqs.Find(id);
            db.Faqs.Remove(faqs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaparKurye/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaparKurye.AC;
using System.IO;

namespace CaparKurye.Areas.Admin.Controllers
{
    public class NewsController : Controller
    {
        private AC.AppContext db = new AC.AppContext();

        public bool UserCheck()
        {
            if (Session["adminID"] != null && Session["adminName"] != null)
            {
                TempData["Message"] = null;
                return true;
            }
            else
            {
                TempData["Message"] = "Lütfen Admin Girişi Yapınız";
                return false;
            }
        }

        // GET: News
        public ActionResult Index()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            var news = db.News.Include(n => n.Pictures);
            return View(news.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name");
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "title,subtitle,summary,content,pictureID")] News news, HttpPostedFileBase file)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.AddHours(11).ToString("MM-dd-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/public/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        Pictures pictures = new Pictures();
                        pictures.title = file.FileName;
                        pictures.name = file.FileName;
                        db.Pictures.Add(pictures);
                        db.SaveChanges();
                        news.pictureID = pictures.pictureID;
                    }
                }
                news.date = DateTime.Now;
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name", news.pictureID);
            return View(news);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name", news.pictureID);
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "newsID,title,subtitle,summary,content,pictureID")] News news, HttpPostedFileBase file)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileNameWithoutExtension(file.FileName) + "-" + DateTime.Now.AddHours(11).ToString("MM-dd-yyyy-hh-mm-ss") + Path.GetExtension(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/public/UploadedFiles"), _FileName);
                        file.SaveAs(_path);
                        Pictures pictures = new Pictures();
                        pictures.title = file.FileName;
                        pictures.name = file.FileName;
                        db.Pictures.Add(pictures);
                        db.SaveChanges();
                        news.pictureID = pictures.pictureID;
                    }
                }
                news.title = news.title.ToString().Trim();
                news.summary = news.summary.ToString().Trim();
                news.subtitle = news.subtitle.ToString().Trim();
                news.content = news.content.ToString().Trim();
                news.date = DateTime.Now;
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "name", news.pictureID);
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaparKurye/Areas/Admin/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaparKurye.AC;

namespace CaparKurye.Areas.Admin.Controllers
{
    public class PagesController : Controller
    {
        private AC.AppContext db = new AC.AppContext();

        public bool UserCheck()
        {
            if (Session["adminID"] != null && Session["adminName"] != null)
            {
                TempData["Message"] = null;
                return true;
            }
            else
            {
                TempData["Message"] = "Lütfen Admin Girişi Yapınız";
                return false;
            }
        }

        // GET: Pages
        public ActionResult Index()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            var pages = db.Pages.Include(p => p.Pictures);
            return View(pages.ToList());
        }

        // GET: Pages/Details/5
        public ActionResult Details(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Page page = db.Pages.Find(id);
            if (page == null)
            {
                return HttpNotFound();
            }
            return View(page);
        }

        // GET: Pages/Create
        public ActionResult Create()
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title");
            return View();
        }

        // POST: Pages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "pageID,pageName,title,subtitle,content,pictureID,description,keywords")] Page page)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (ModelState.IsValid)
            {
                db.Pages.Add(page);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title", page.pictureID);
            return View(page);
        }

        // GET: Pages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Page page = db.Pages.Find(id);
            if (page == null)
            {
                return HttpNotFound();
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title", page.pictureID);
            return View(page);
        }

        // POST: Pages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "pageID,title,subtitle,content,pictureID,description,keywords")] Page page)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });
            Page obj = db.Pages.Find(page.pageID);
            if (ModelState.IsValid)
            {
                obj.title = page.title.Trim();
                obj.subtitle = page.subtitle.Trim();
                obj.content = page.content.Trim();
                obj.pictureID = page.pictureID;
                obj.description = page.description.Trim();
                obj.keywords = page.keywords.Trim();
                db.Entry(obj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pictureID = new SelectList(db.Pictures, "pictureID", "title", page.pictureID);
            return View(page);
        }

        // GET: Pages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Page page = db.Pages.Find(id);
            if (page == null)
            {
                return HttpNotFound();
            }
            return View(page);
        }

        // POST: Pages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login", "Admins", new { area = "Admin" });

            Page page = db.Pages.Find(id);
            db.Pages.Remove(page);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaparKurye/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title - Admin Portal</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" />

    @Styles.Render("~/Areas/Admin/Content/css/font-awesome.css")
    @Styles.Render("~/Areas/Admin/Content/css/bootstrap.min.css")
    @Styles.Render("~/Areas/Admin/Content/css/font-awesome.css")
    @Styles.Render("~/Areas/Admin/Content/css/animate.css")
    @Styles.Render("~/Areas/Admin/Content/dist/css/swiper.min.css")
    @Styles.Render("~/Areas/Admin/Content/css/style.css")
    @Styles.Render("~/Areas/Admin/Content/dist/css/bootstrap-select.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Areas/Admin/Content/js/jquery-1.9.1.min.js")
    @Scripts.Render("~/Areas/Admin/Content/js/bootstrap.min.js")
    @Scripts.Render("~/Areas/Admin/Content/dist/js/bootstrap-select.js")
    @Scripts.Render("~/Areas/Admin/Content/dist/js/swiper.min.js")
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $(".accordion dt").click(function () {
                $(this).next().slideToggle();
            });
        });
    </script>
    <style>
        .formtable {
            text-align: left;
            display: inline-block;
            width: 100%;
            margin: 20px auto;
            padding: 25px;
            border: dashed 1px #b5b5b5;
            background-color: white;
        }

        .progress-bar {
            animation: slideInLeft .6s ease;
            -webkit-animation: slideInLeft .6s ease;
        }
    </style>
</head>
<body>


    <div class="left-menu">
        <a href="@Url.Action("Dashboard", "Admins")"><div class="logo">YÖNETİM PANELİ<small>Çapar Kargo ve Kurye</small></div></a>

        <ul class="menu">
            @if (Session["adminType"].ToString() == "Admin")
            {
                <li>
                    <a href="#" onclick="$(this).next().slideToggle();"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Yönetim İşlemleri <span class="caret"></span></a>
                    <ul>
                        <li>@Html.ActionLink("Raporlar", "Dashboard", "Admins")</li>
                        <li>@Html.ActionLink("Yöneticiler", "Index", "Admins")</li>
                    </ul>
                </li>
                <li><a href="@Url.Action("Index", "BankAccounts")"><i class="fa fa-credit-card-alt" aria-hidden="true"></i> Banka Hesapları</a></li>
                <li><a href="@Url.Action("Index", "Faqs")"><i class="fa fa-question-circle" aria-hidden="true"></i> Sıkça Sorulan Sorular</a></li>
                <li><a href="@Url.Action("Index", "Files")"><i class="fa fa-wpforms" aria-hidden="true"></i> Belgeler</a></li>
                <li><a href="@Url.Action("Index", "News")"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Haberler</a></li>
                <li><a href="@Url.Action("Index", "Notifications")"><i class="fa fa-bullhorn" aria-hidden="true"></i> Duyurular</a></li>
                <li><a href="@Url.Action("Index", "Pages")"><i class="fa fa-file-o" aria-hidden="true"></i> Sayfalar</a></li>
                <li><a href="@Url.Action("Index", "Pictures")"><i class="fa fa-picture-o" aria-hidden="true"></i> Resimler</a></li>
                <li><a href="@Url.Action("Index", "Services")"><i class="fa fa-university" aria-hidden="true"></i> Hizmetler</a></li>
                <li><a href="@Url.Action("Index", "Sliders")"><i class="fa fa-exchange" aria-hidden="true"></i> Slider</a></li>
                <li><a href="@Url.Action("Create", "AdminUsers")"><i class="fa fa-users" aria-hidden="true"></i> Üyeler</a></li>
                <li><a href="@Url.Action("Index", "Couriers")"><i class="fa fa-motorcycle" aria-hidden="true"></i> Kurye Siparişleri</a></li>
            }

            @if (Session["adminType"].ToString() == "Asistan")
            {
                <li><a href="@Url.Action("Index", "Faqs")"><i class="fa fa-question-circle" aria-hidden="true"></i> Sıkça Sorulan Sorular</a></li>
                <li><a href="@Url.Action("Index", "Files")"><i class="fa fa-wpforms" aria-hidden="true"></i> Belgeler</a></li>
                <li><a href="@Url.Action("Index", "News")"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Haberler</a></li>
                <li><a href="@Url.Action("Index", "Notifications")"><i class="fa fa-bullhorn" aria-hidden="true"></i> Duyurular</a></li>
                <li><a href="@Url.Action("Index", "Pages")"><i class="fa fa-file-o" aria-hidden="true"></i> Sayfalar</a></li>
                <li><a href="@Url.Action("Index", "Pictures")"><i class="fa fa-picture-o" aria-hidden="true"></i> Resimler</a></li>
                <li><a href="@Url.Action("Index", "Services")"><i class="fa fa-university" aria-hidden="true"></i> Hizmetler</a></li>
                <li><a href="@Url.Action("Index", "Sliders")"><i class="fa fa-exchange" aria-hidden="true"></i> Slider</a></li>
                <li><a href="@Url.Action("Index", "AdminUsers")"><i class="fa fa-users" aria-hidden="true"></i> Üyeler</a></li>
                <li><a href="@Url.Action("Index", "Couriers")"><i class="fa fa-motorcycle" aria-hidden="true"></i> Kurye Siparişleri</a></li>
            }
            @if (Session["adminType"].ToString() == "Muhasebe")
            {
                <li><a href="@Url.Action("Index", "AdminUsers")"><i class="fa fa-users" aria-hidden="true"></i> Üyeler</a></li>
                <li><a href="@Url.Action("Index", "Couriers")"><i class="fa fa-motorcycle" aria-hidden="true"></i> Kurye Siparişleri</a></li>
            }



        </ul>

    </div>

    <div class="body">
        <header>
            <div class="nav" onclick="$('body').toggleClass('active');"><i class="fa fa-bars" aria-hidden="true"></i></div>

            <div class="pull-right">
                <a href="@Url.Action("Profile", "Admins", new { Area = "Admin"})">
                    <div class="menu" data-toggle="tooltip" data-placement="bottom" title="@Session["adminName"]">
                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                    </div>
                </a>
                @if (Session["adminType"].ToString() == "Admin")
                {
                    <a href="@Url.Action( "Edit", "Settings",new { id=1})">
                        <div class="menu" data-toggle="tooltip"
                             -placement="bottom" title="Ayarlar">
                            <i class="fa fa-cog" aria-hidden="true"></i>
                        </div>
                    </a>
                }
                <a href="@Url.Action("Logout", "Admins")"><div class="logout" data-toggle="tooltip" data-placement="bottom" title="Çıkış"><i class="fa fa-sign-out" aria-hidden="true"></i></div></a>
            </div>

        </header>

        <div class="content">
            <div class="bar"><span></span></div>
            @RenderBody()
        </div>
    </div>
</body>
</html>