CaparKurye/Areas/Admin/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaparKurye.AC;

namespace CaparKurye.Areas.Admin.Controllers
{
    public class AdminsController : Controller
    {
        private AC.AppContext db = new AC.AppContext();

        public bool UserCheckBasic()
        {
            if (Session["adminID"] != null && Session["adminName"] != null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public bool UserCheck()
        {
            if (Session["adminID"] != null && Session["adminName"] != null)
            {
                TempData["Message"] = null;
                return true;
            }
            else
            {
                TempData["Message"] = "Lütfen Admin Girişi Yapınız";
                return false;
            }
        }

        // GET: Admins
        public ActionResult Index()
        {
            if (!this.UserCheck()) return RedirectToAction("Dashboard");

            int id = Convert.ToInt32(Session["adminID"]);
            return View(db.Admins.Where(x=>x.adminID!=id).ToList());
        }

        // GET: Login
        public ActionResult Login()
        {
            if (this.UserCheckBasic()) return RedirectToAction("Dashboard");

            return View();
        }

        // GET: Dashboard
        public ActionResult Dashboard()
        {
            if (!this.UserCheck()) return RedirectToAction("Login");
            int id = Convert.ToInt32(Session["adminID"].ToString());
            var obj2 = db.Admins.Where(a => a.adminID.Equals(id)).FirstOrDefault();
            if (obj2.adminType != "Admin") return RedirectToAction("Index","Couriers");
            ViewBag.individualCount = db.Users.Where(a => a.type.Equals("individual")).Count();
            ViewBag.corporateCount = db.Users.Where(a => a.type.Equals("corporate")).Count();
            List<Couriers> q = db.Couriers.OrderByDescending(x=>x.courierID).ToList();
            ViewBag.courierRequests = q;
            ViewBag.courierCount = q.Count();
            ViewBag.successCount = q.Where(x=>x.status.Equals("Onaylandı")).Count();
            ViewBag.waitingCount = q.Where(x => x.status.Equals("Bekliyor")).Count();
            ViewBag.cancelCount = q.Where(x => x.status.Equals("İptal")).Count();

            ViewBag.paymentSuccessCount = q.Where(x => x.Payments.paymentStatus.Equals("Ödendi")).Count();
            ViewBag.paymentWaitingCount = q.Where(x => x.Payments.paymentStatus.Equals("Ödenmedi")).Count();
            ViewBag.paymentCancelCount = q.Where(x => x.Payments.paymentStatus.Equals("İade")).Count();

            ViewBag.years = db.Couriers.GroupBy(
                p => p.date.Value.Year,
                (key, g) => new {year = key,count = g.Count()}).OrderByDescending(x => x.year).Select(z => z.year).ToList();
            return View(q);
        }

        // GET: Dashboard
        public ActionResult Logout()
        {
            Session["adminID"] = null;
            Session["adminType"] = null;
            Session["adminName"] = null;
            return RedirectToAction("Login");
        }


        // POST: Admins/Login
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "adminName,password")] Admins admins)
        {
            if (this.UserCheckBasic()) return RedirectToAction("Dashboard");

            if (ModelState.IsValid)
            {
                var obj = db.Admins.Where(a => a.adminName.Equals(admins.adminName) && a.password.Equals(admins.password)).FirstOrDefault();
                if (obj != null)
                {
                    Session["adminID"] = obj.adminID.ToString();
                    Session["adminType"] = obj.adminType.ToString();
                    Session["adminName"] = obj.adminName.ToString();
                    return RedirectToAction("Dashboard");
                }
                else
                {
                    TempData["Message"] = "Kullanıcı Adı veya Şifre Hatalı";
                    return RedirectToAction("Login");
                }
            }

            return View();
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (!this.UserCheck()) return RedirectToAction("Login");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admins admins = db.Admins.Find(id);
            if (admins == null)
            {
                return HttpNotFound();
            }
            return View(admins);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            if (!this.UserCheck()) return RedirectToAction("Login");

            return View();
        }

        // GET: Admins/GetCouriersByDate
        [HttpPost]
        public ActionResult GetCouriersByDate(string firstDate, string secondDate)
        {
            if (!this.UserCheck()) return Json(new { code=400, message = "Üye Girişi Yapınız" }, JsonRequestBehavior.AllowGet);
            if (firstDate == "")
            {
                firstDate = "2000-01-01";
            }
            if (secondDate == "")
            {
                secondDate = "2000-01-01";
            }
            DateTime firstDateConvert = DateTime.ParseExact(firstDate+ " 00:00:00", "yyyy-MM-dd HH:mm:ss",
                                       System.Globalization.CultureInfo.InvariantCulture);
            DateTime secondDateConvert = DateTime.ParseExact(secondDate+ " 23:59:59", "yyyy-MM-dd HH:mm:ss",
                                       System.Globalization.CultureInfo.InvariantCulture);

            var top3FromDistrict = db.Couriers.Where(a => (a.date >= firstDateConvert && a.date <= secondDateConvert)).GroupBy(
                p => p.fromDistrict,
                (key, g) => new { fromDistrict = key.Trim(), count = g.Count() }).OrderByDescending(x => x.count);

            var couriers = db.Couriers.Where(a => (a.date >= firstDateConvert && a.date <= secondDateConvert)).GroupBy(
                p => p.postType,
                (key, g) => new { postType = key.Trim(), count = g.Count() });

            return Json(new { code = 200, data = new { couriers = couriers, top3FromDistrict = top3FromDistrict } }, JsonRequestBehavior.AllowGet);
        }
        // GET: Admins/GetCouriersByDateAll
        [HttpPost]
        public ActionResult GetCouriersByDateAll(string firstDate, string secondDate)
        {
            if (!this.UserCheck()) return Json(new { code = 400, message = "Üye Girişi Yapınız" }, JsonRequestBehavior.AllowGet);
            if (firstDate == ""){
                firstDate = "2000-01-01";
            }
            if (secondDate == ""){
                secondDate = "2000-01-01";
            }

            DateTime firstDateConvert = DateTime.ParseExact(firstDate + " 00:00:00", "yyyy-MM-dd HH:mm:ss",
                                       System.Globalization.CultureInfo.InvariantCulture);
            DateTime secondDateConvert = DateTime.ParseExact(secondDate + " 23:59:59", "yyyy-MM-dd HH:mm:ss",
                                       System.Globalization.CultureInfo.InvariantCulture);


            var couriers = db.Couriers.Where(a => (a.date >= firstDateConvert && a.date <= secondDateConvert)).OrderByDescending(x => x.courierID).Select(x => new { x.postType, x.status, x.Users.userID, x.post, x.count, x.Payments.paymentType, x.Payments.cost, x.Payments.tax, x.Payments.totalCost, x.date, x.courierID, x.Payments.paymentStatus });

            return Json(new { code = 200, data = new { couriers = couriers } }, JsonRequestBehavior.AllowGet);
        }

        // GET: Admins/GetCiroByDate
        [HttpPost]
        public ActionResult GetCiroByDate(string firstDate, string secondDate)
        {
            if (!this.UserCheck()) return Json(new { code = 400, message = "Üye Girişi Yapınız" }, JsonRequestBehavior.AllowGet);
            if (firstDate == "")
            {
                firstDate = "2000-01-01";
            }
            if (secondDate == "")
            {
                secondDate = "2000-01-01";
            }
            DateTime firstDateConvert = DateTime.ParseExact(firstDate + " 00:00:00", "yyyy-MM-dd HH:mm:ss",
                                       System.Globalization.CultureInfo.InvariantCulture);
            DateTime secondDateConvert = DateTime.ParseExact(secondDate + " 23:59:59", "yyyy-MM-dd HH:mm:ss",
                                       System.Globalization.CultureInfo.InvariantCulture);

           
            var couriers = db.Couriers.Where(a => (a.date >= firstDateConvert && a.date <= secondDateConvert)).Where(z=>z.Payments.paymentStatus.Equals("Ödendi")).OrderByDescending(x=>x.courierID).Select(x=> new {x.postType , x.status,x.Users.userID,x.post,x.count, x.Payments.paymentType, x.Payments.cost, x.Payments.tax, x.Payments.totalCost,x.date,x.courierID });

            return Json(new { code = 200, data = new { couriers = couriers } }, JsonRequestBehavior.AllowGet);
        }


        // GET: Admins/GetYearlyPayments
        [HttpPost]
        public ActionResult GetYearlyPayments(int year)
        {
            if (!this.UserCheck()) return Json(new { code=400, message = "Üye Girişi Yapınız" }, JsonRequestBehavior.AllowGet);

            var paymentTypes = db.Couriers.GroupBy(
                p => p.Payments.paymentType,
                (key, g) => new { paymentType = key, count = g.Count() });

            var couriers = db.Couriers.Where(x => x.date.Value.Year.Equals(year));

CaparKurye/Areas/Admin/Views/Admins/Create.cshtml
@model CaparKurye.Admins

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}




<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Yöneticiler</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                if (TempData["Message"] != null)
                {
                    <div class="form-group" style="text-align: center;">
                        <div class="col-md-12">
                            <div class="alert alert-danger">@TempData["Message"]</div>
                        </div>
                    </div>
                }

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.adminName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.adminName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.adminName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.adminType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <select class="form-control selectpicker" id="adminType" name="adminType" title="Seçim Yapınız">
                            <option value="Admin" selected="selected">Admin</option>
                            <option value="Asistan">Asistan</option>
                            <option value="Muhasebe">Muhasebe</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-offset-2 col-md-4 col-xs-6">
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-success pull-left" />
                    </div>
                </div>

            }
            <div class="col-xs-6 col-md-4">
                <div class="form-group">
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default pull-right" })
                </div>
            </div>

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/Admins/Delete.cshtml
@model CaparKurye.Admins

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Silmek İstediğinize Emin misiniz?</h3>
    <div>
        <h4>Admins</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.adminName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.adminName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.password)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.date)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

CaparKurye/Areas/Admin/Views/Admins/Details.cshtml
@model CaparKurye.Admins

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

            <h4>Admins</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.adminName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.adminName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.password)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.password)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.date)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.date)
                </dd>

            </dl>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    @Html.ActionLink("Düzenle", "Edit", new { id = Model.adminID }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default" })
                </div>
            </div>
            
</body>
</html>

CaparKurye/Areas/Admin/Views/Admins/Edit.cshtml
@model CaparKurye.Admins

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script>
    $(function () {
        $("#adminType").val("@Html.Raw(Model.adminType)");
    });
</script>


<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Yöneticiler</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.adminName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.adminName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.adminName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.adminType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <select class="form-control selectpicker" id="adminType" name="adminType" title="Seçim Yapınız">
                            <option value="Admin">Admin</option>
                            <option value="Asistan">Asistan</option>
                            <option value="Muhasebe">Muhasebe</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-offset-2 col-md-4 col-xs-6">
                    <div class="form-group pull-left">
                        <input type="submit" value="Güncelle" class="btn btn-success" />
                    </div>
                </div>

            }
            <div class="col-xs-6 col-md-4">
                <div class="form-group pull-right">
                    <div style="display:inline-block">
                        @using (Html.BeginForm("Delete", "Admins", new { id = Model.adminType }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="submit" value="Sil" class="btn btn-danger" />
                        }
                    </div>
                    @Html.ActionLink("Listeye Geri Dön", "Index", new { }, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>

    </div>
</div>

CaparKurye/Areas/Admin/Views/Admins/Index.cshtml
@model IEnumerable<CaparKurye.Admins>

@{
    ViewBag.Title = "Yöneticiler";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}




<div class="col-xs-12 col-sm-12">

    <div class="page">

        <h4 class="title"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Yöneticiler</h4>
        <div class="col-xs-12 col-sm-12">

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.adminName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.adminType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.date)
                    </th>
                    <th>
                        @if (Session["adminType"].ToString() == "Admin")
                        {
                            @Html.ActionLink("Yeni Ekle", "Create", new { }, new { @class = "btn btn-primary btn-xs pull-right" })
                        }
                    </th>
                </tr>


                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.adminName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.adminType)
                        </td>
                        <td>
                            @item.date.ToShortDateString()
                        </td>

                        <td class="text-right">

                            @if (Session["adminType"].ToString() == "Admin")
                            {
                                @Html.ActionLink("Düzenle", "Edit", new { id = item.adminID }, new { @class = "btn btn-warning btn-xs" })
                            }

                        </td>
                    </tr>
                }

            </table>

        </div>
    </div>
</div>

CaparKurye/Areas/Admin/Views/Admins/Login.cshtml
@model CaparKurye.Admins

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Admin</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    @Styles.Render("~/Areas/Admin/Content/css/font-awesome.css")
    @Styles.Render("~/Areas/Admin/Content/css/bootstrap.min.css")
    @Styles.Render("~/Areas/Admin/Content/css/font-awesome.css")
    @Styles.Render("~/Areas/Admin/Content/css/animate.css")
    @Styles.Render("~/Areas/Admin/Content/css/style.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Areas/Admin/Content/js/jquery-1.9.1.min.js")
    @Scripts.Render("~/Areas/Admin/Content/js/bootstrap.min.js")
</head>
<body class="login background">

    <div class="panel">
        <h3>Yönetim Paneli</h3>
        <hr>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @if (TempData["Message"] != null)
                {
                    <div class="form-group" style="text-align: center;">
                        <div class="text-danger">@TempData["Message"]</div>
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(model => model.adminName, htmlAttributes: new { @class = "col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.adminName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.adminName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "col-md-12" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" value="Giriş Yap" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>

CaparKurye/Areas/Admin/Views/Admins/Profile.cshtml
@model CaparKurye.Admins

@{
    ViewBag.Title = "Profilim";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script>
    $("input").each(function () { $(this).val($(this).val().trim()); })
</script>
@if (TempData["Message"] != null)
{
    <div id="alertBox" class="alert alert-danger" role="alert">@TempData["Message"]</div>
}


<div class="col-sm-12 col-md-12">
    <div class="page">
        <h4 class="title"><i class="fa fa-user-circle" aria-hidden="true"></i> Profilim</h4>

        <div class="form-horizontal" style="padding: 0px 15px;">
            <div class="col-md-offset-4 col-md-4">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.adminName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.adminName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.adminName, "", new { @class = "text-danger" })
                    </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>

                <div class="form-group">
                        <input type="submit" value="Güncelle" class="btn btn-success pull-right" />
                </div>

            }</div>

        </div>

    </div>
</div>